//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadBooksEasy.Domain.Entities2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int IdBookmark { get; set; }
        public int IdUser { get; set; }
        public int IdBook { get; set; }
        public int numberOfPage { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
