//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadBooksEasy.Domain.Entities2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersBook
    {
        public int IdUsers { get; set; }
        public int idBooks { get; set; }
        public Nullable<bool> usingFieldRating { get; set; }
        public Nullable<double> ratingForBook { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
